global using FluentAssertions;
global using System.Collections;
global using System.Diagnostics.CodeAnalysis;
global using System.Globalization;
global using System.Text;
global using System.Xml;
global using System.Xml.XPath;
global using System.Xml.Xsl;
global using Xunit;
